package com.generator.mapper;

import com.generator.pojo.RAmRoles;
import com.generator.pojo.RAmRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RAmRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int countByExample(RAmRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int deleteByExample(RAmRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int insert(RAmRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int insertSelective(RAmRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    List<RAmRoles> selectByExample(RAmRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    RAmRoles selectByPrimaryKey(Integer pkRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RAmRoles record, @Param("example") RAmRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RAmRoles record, @Param("example") RAmRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RAmRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_Roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RAmRoles record);
}