package com.generator.mapper;

import com.generator.pojo.RAmUserRoles;
import com.generator.pojo.RAmUserRolesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RAmUserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int countByExample(RAmUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int deleteByExample(RAmUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pkUserRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int insert(RAmUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int insertSelective(RAmUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    List<RAmUserRoles> selectByExample(RAmUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    RAmUserRoles selectByPrimaryKey(String pkUserRoleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RAmUserRoles record, @Param("example") RAmUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RAmUserRoles record, @Param("example") RAmUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RAmUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RAmUserRoles record);
}