package com.generator.mapper;

import com.generator.pojo.RCbdEconomicActivityType;
import com.generator.pojo.RCbdEconomicActivityTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RCbdEconomicActivityTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int countByExample(RCbdEconomicActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int deleteByExample(RCbdEconomicActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pkEconomicActivityTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int insert(RCbdEconomicActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int insertSelective(RCbdEconomicActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    List<RCbdEconomicActivityType> selectByExample(RCbdEconomicActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    RCbdEconomicActivityType selectByPrimaryKey(Integer pkEconomicActivityTypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RCbdEconomicActivityType record, @Param("example") RCbdEconomicActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RCbdEconomicActivityType record, @Param("example") RCbdEconomicActivityTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RCbdEconomicActivityType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RCbdEconomicActivityType record);
}