package com.generator.mapper;

import com.generator.pojo.RLmApplicationAttached;
import com.generator.pojo.RLmApplicationAttachedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RLmApplicationAttachedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int countByExample(RLmApplicationAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int deleteByExample(RLmApplicationAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pkApplicationAttachedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int insert(RLmApplicationAttached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int insertSelective(RLmApplicationAttached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    List<RLmApplicationAttached> selectByExample(RLmApplicationAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    RLmApplicationAttached selectByPrimaryKey(String pkApplicationAttachedid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RLmApplicationAttached record, @Param("example") RLmApplicationAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RLmApplicationAttached record, @Param("example") RLmApplicationAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RLmApplicationAttached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RLmApplicationAttached record);
}