package com.generator.mapper;

import com.generator.pojo.RLmApplicationItemAssets;
import com.generator.pojo.RLmApplicationItemAssetsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RLmApplicationItemAssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int countByExample(RLmApplicationItemAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int deleteByExample(RLmApplicationItemAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pkApplicationItemAssetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int insert(RLmApplicationItemAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int insertSelective(RLmApplicationItemAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    List<RLmApplicationItemAssets> selectByExample(RLmApplicationItemAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    RLmApplicationItemAssets selectByPrimaryKey(String pkApplicationItemAssetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RLmApplicationItemAssets record, @Param("example") RLmApplicationItemAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RLmApplicationItemAssets record, @Param("example") RLmApplicationItemAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RLmApplicationItemAssets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RLmApplicationItemAssets record);
}