package com.generator.mapper;

import com.generator.pojo.RLmHistory;
import com.generator.pojo.RLmHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RLmHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int countByExample(RLmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int deleteByExample(RLmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String pkLmHistoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int insert(RLmHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int insertSelective(RLmHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    List<RLmHistory> selectByExample(RLmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    RLmHistory selectByPrimaryKey(String pkLmHistoryid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RLmHistory record, @Param("example") RLmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RLmHistory record, @Param("example") RLmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RLmHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RLmHistory record);
}