package com.generator.pojo;

import java.util.ArrayList;
import java.util.List;

public class RAmUserRolesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public RAmUserRolesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkUserRoleidIsNull() {
            addCriterion("PK_User_RoleID is null");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidIsNotNull() {
            addCriterion("PK_User_RoleID is not null");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidEqualTo(String value) {
            addCriterion("PK_User_RoleID =", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidNotEqualTo(String value) {
            addCriterion("PK_User_RoleID <>", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidGreaterThan(String value) {
            addCriterion("PK_User_RoleID >", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidGreaterThanOrEqualTo(String value) {
            addCriterion("PK_User_RoleID >=", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidLessThan(String value) {
            addCriterion("PK_User_RoleID <", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidLessThanOrEqualTo(String value) {
            addCriterion("PK_User_RoleID <=", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidLike(String value) {
            addCriterion("PK_User_RoleID like", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidNotLike(String value) {
            addCriterion("PK_User_RoleID not like", value, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidIn(List<String> values) {
            addCriterion("PK_User_RoleID in", values, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidNotIn(List<String> values) {
            addCriterion("PK_User_RoleID not in", values, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidBetween(String value1, String value2) {
            addCriterion("PK_User_RoleID between", value1, value2, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andPkUserRoleidNotBetween(String value1, String value2) {
            addCriterion("PK_User_RoleID not between", value1, value2, "pkUserRoleid");
            return (Criteria) this;
        }

        public Criteria andFkUseridIsNull() {
            addCriterion("FK_UserID is null");
            return (Criteria) this;
        }

        public Criteria andFkUseridIsNotNull() {
            addCriterion("FK_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andFkUseridEqualTo(String value) {
            addCriterion("FK_UserID =", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridNotEqualTo(String value) {
            addCriterion("FK_UserID <>", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridGreaterThan(String value) {
            addCriterion("FK_UserID >", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridGreaterThanOrEqualTo(String value) {
            addCriterion("FK_UserID >=", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridLessThan(String value) {
            addCriterion("FK_UserID <", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridLessThanOrEqualTo(String value) {
            addCriterion("FK_UserID <=", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridLike(String value) {
            addCriterion("FK_UserID like", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridNotLike(String value) {
            addCriterion("FK_UserID not like", value, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridIn(List<String> values) {
            addCriterion("FK_UserID in", values, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridNotIn(List<String> values) {
            addCriterion("FK_UserID not in", values, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridBetween(String value1, String value2) {
            addCriterion("FK_UserID between", value1, value2, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkUseridNotBetween(String value1, String value2) {
            addCriterion("FK_UserID not between", value1, value2, "fkUserid");
            return (Criteria) this;
        }

        public Criteria andFkRoleIsNull() {
            addCriterion("FK_Role is null");
            return (Criteria) this;
        }

        public Criteria andFkRoleIsNotNull() {
            addCriterion("FK_Role is not null");
            return (Criteria) this;
        }

        public Criteria andFkRoleEqualTo(Integer value) {
            addCriterion("FK_Role =", value, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleNotEqualTo(Integer value) {
            addCriterion("FK_Role <>", value, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleGreaterThan(Integer value) {
            addCriterion("FK_Role >", value, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleGreaterThanOrEqualTo(Integer value) {
            addCriterion("FK_Role >=", value, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleLessThan(Integer value) {
            addCriterion("FK_Role <", value, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleLessThanOrEqualTo(Integer value) {
            addCriterion("FK_Role <=", value, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleIn(List<Integer> values) {
            addCriterion("FK_Role in", values, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleNotIn(List<Integer> values) {
            addCriterion("FK_Role not in", values, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleBetween(Integer value1, Integer value2) {
            addCriterion("FK_Role between", value1, value2, "fkRole");
            return (Criteria) this;
        }

        public Criteria andFkRoleNotBetween(Integer value1, Integer value2) {
            addCriterion("FK_Role not between", value1, value2, "fkRole");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_AM_User_Roles
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}