package com.generator.pojo;

public class RAmUserRoles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_AM_User_Roles.PK_User_RoleID
     *
     * @mbggenerated
     */
    private String pkUserRoleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_AM_User_Roles.FK_UserID
     *
     * @mbggenerated
     */
    private String fkUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_AM_User_Roles.FK_Role
     *
     * @mbggenerated
     */
    private Integer fkRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_AM_User_Roles.PK_User_RoleID
     *
     * @return the value of R_AM_User_Roles.PK_User_RoleID
     *
     * @mbggenerated
     */
    public String getPkUserRoleid() {
        return pkUserRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_AM_User_Roles.PK_User_RoleID
     *
     * @param pkUserRoleid the value for R_AM_User_Roles.PK_User_RoleID
     *
     * @mbggenerated
     */
    public void setPkUserRoleid(String pkUserRoleid) {
        this.pkUserRoleid = pkUserRoleid == null ? null : pkUserRoleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_AM_User_Roles.FK_UserID
     *
     * @return the value of R_AM_User_Roles.FK_UserID
     *
     * @mbggenerated
     */
    public String getFkUserid() {
        return fkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_AM_User_Roles.FK_UserID
     *
     * @param fkUserid the value for R_AM_User_Roles.FK_UserID
     *
     * @mbggenerated
     */
    public void setFkUserid(String fkUserid) {
        this.fkUserid = fkUserid == null ? null : fkUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_AM_User_Roles.FK_Role
     *
     * @return the value of R_AM_User_Roles.FK_Role
     *
     * @mbggenerated
     */
    public Integer getFkRole() {
        return fkRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_AM_User_Roles.FK_Role
     *
     * @param fkRole the value for R_AM_User_Roles.FK_Role
     *
     * @mbggenerated
     */
    public void setFkRole(Integer fkRole) {
        this.fkRole = fkRole;
    }
}