package com.generator.pojo;

import java.util.ArrayList;
import java.util.List;

public class RCbdEconomicActivityTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public RCbdEconomicActivityTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkEconomicActivityTypeidIsNull() {
            addCriterion("PK_Economic_Activity_TypeID is null");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidIsNotNull() {
            addCriterion("PK_Economic_Activity_TypeID is not null");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidEqualTo(Integer value) {
            addCriterion("PK_Economic_Activity_TypeID =", value, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidNotEqualTo(Integer value) {
            addCriterion("PK_Economic_Activity_TypeID <>", value, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidGreaterThan(Integer value) {
            addCriterion("PK_Economic_Activity_TypeID >", value, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("PK_Economic_Activity_TypeID >=", value, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidLessThan(Integer value) {
            addCriterion("PK_Economic_Activity_TypeID <", value, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidLessThanOrEqualTo(Integer value) {
            addCriterion("PK_Economic_Activity_TypeID <=", value, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidIn(List<Integer> values) {
            addCriterion("PK_Economic_Activity_TypeID in", values, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidNotIn(List<Integer> values) {
            addCriterion("PK_Economic_Activity_TypeID not in", values, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidBetween(Integer value1, Integer value2) {
            addCriterion("PK_Economic_Activity_TypeID between", value1, value2, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andPkEconomicActivityTypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("PK_Economic_Activity_TypeID not between", value1, value2, "pkEconomicActivityTypeid");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNull() {
            addCriterion("Type_Name is null");
            return (Criteria) this;
        }

        public Criteria andTypeNameIsNotNull() {
            addCriterion("Type_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTypeNameEqualTo(String value) {
            addCriterion("Type_Name =", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotEqualTo(String value) {
            addCriterion("Type_Name <>", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThan(String value) {
            addCriterion("Type_Name >", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("Type_Name >=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThan(String value) {
            addCriterion("Type_Name <", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLessThanOrEqualTo(String value) {
            addCriterion("Type_Name <=", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameLike(String value) {
            addCriterion("Type_Name like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotLike(String value) {
            addCriterion("Type_Name not like", value, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameIn(List<String> values) {
            addCriterion("Type_Name in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotIn(List<String> values) {
            addCriterion("Type_Name not in", values, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameBetween(String value1, String value2) {
            addCriterion("Type_Name between", value1, value2, "typeName");
            return (Criteria) this;
        }

        public Criteria andTypeNameNotBetween(String value1, String value2) {
            addCriterion("Type_Name not between", value1, value2, "typeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_CBD_Economic_Activity_Type
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}