package com.generator.pojo;

public class RCbdEconomicActivityType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_CBD_Economic_Activity_Type.PK_Economic_Activity_TypeID
     *
     * @mbggenerated
     */
    private Integer pkEconomicActivityTypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_CBD_Economic_Activity_Type.Type_Name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_CBD_Economic_Activity_Type.PK_Economic_Activity_TypeID
     *
     * @return the value of R_CBD_Economic_Activity_Type.PK_Economic_Activity_TypeID
     *
     * @mbggenerated
     */
    public Integer getPkEconomicActivityTypeid() {
        return pkEconomicActivityTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_CBD_Economic_Activity_Type.PK_Economic_Activity_TypeID
     *
     * @param pkEconomicActivityTypeid the value for R_CBD_Economic_Activity_Type.PK_Economic_Activity_TypeID
     *
     * @mbggenerated
     */
    public void setPkEconomicActivityTypeid(Integer pkEconomicActivityTypeid) {
        this.pkEconomicActivityTypeid = pkEconomicActivityTypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_CBD_Economic_Activity_Type.Type_Name
     *
     * @return the value of R_CBD_Economic_Activity_Type.Type_Name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_CBD_Economic_Activity_Type.Type_Name
     *
     * @param typeName the value for R_CBD_Economic_Activity_Type.Type_Name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}