package com.generator.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RLmApplicationItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public RLmApplicationItemsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkApplicationItemidIsNull() {
            addCriterion("PK_Application_ItemID is null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidIsNotNull() {
            addCriterion("PK_Application_ItemID is not null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidEqualTo(String value) {
            addCriterion("PK_Application_ItemID =", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidNotEqualTo(String value) {
            addCriterion("PK_Application_ItemID <>", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidGreaterThan(String value) {
            addCriterion("PK_Application_ItemID >", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidGreaterThanOrEqualTo(String value) {
            addCriterion("PK_Application_ItemID >=", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidLessThan(String value) {
            addCriterion("PK_Application_ItemID <", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidLessThanOrEqualTo(String value) {
            addCriterion("PK_Application_ItemID <=", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidLike(String value) {
            addCriterion("PK_Application_ItemID like", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidNotLike(String value) {
            addCriterion("PK_Application_ItemID not like", value, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidIn(List<String> values) {
            addCriterion("PK_Application_ItemID in", values, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidNotIn(List<String> values) {
            addCriterion("PK_Application_ItemID not in", values, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidBetween(String value1, String value2) {
            addCriterion("PK_Application_ItemID between", value1, value2, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemidNotBetween(String value1, String value2) {
            addCriterion("PK_Application_ItemID not between", value1, value2, "pkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNull() {
            addCriterion("\"FK_ ApplicationID\" is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNotNull() {
            addCriterion("\"FK_ ApplicationID\" is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" =", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <>", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThan(String value) {
            addCriterion("\"FK_ ApplicationID\" >", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" >=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThan(String value) {
            addCriterion("\"FK_ ApplicationID\" <", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLike(String value) {
            addCriterion("\"FK_ ApplicationID\" like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotLike(String value) {
            addCriterion("\"FK_ ApplicationID\" not like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" not in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" not between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueIsNull() {
            addCriterion("Declared_Value is null");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueIsNotNull() {
            addCriterion("Declared_Value is not null");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueEqualTo(BigDecimal value) {
            addCriterion("Declared_Value =", value, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueNotEqualTo(BigDecimal value) {
            addCriterion("Declared_Value <>", value, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueGreaterThan(BigDecimal value) {
            addCriterion("Declared_Value >", value, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Declared_Value >=", value, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueLessThan(BigDecimal value) {
            addCriterion("Declared_Value <", value, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Declared_Value <=", value, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueIn(List<BigDecimal> values) {
            addCriterion("Declared_Value in", values, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueNotIn(List<BigDecimal> values) {
            addCriterion("Declared_Value not in", values, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Declared_Value between", value1, value2, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andDeclaredValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Declared_Value not between", value1, value2, "declaredValue");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNull() {
            addCriterion("Item_Type is null");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNotNull() {
            addCriterion("Item_Type is not null");
            return (Criteria) this;
        }

        public Criteria andItemTypeEqualTo(String value) {
            addCriterion("Item_Type =", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotEqualTo(String value) {
            addCriterion("Item_Type <>", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThan(String value) {
            addCriterion("Item_Type >", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Item_Type >=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThan(String value) {
            addCriterion("Item_Type <", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThanOrEqualTo(String value) {
            addCriterion("Item_Type <=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLike(String value) {
            addCriterion("Item_Type like", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotLike(String value) {
            addCriterion("Item_Type not like", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeIn(List<String> values) {
            addCriterion("Item_Type in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotIn(List<String> values) {
            addCriterion("Item_Type not in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeBetween(String value1, String value2) {
            addCriterion("Item_Type between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotBetween(String value1, String value2) {
            addCriterion("Item_Type not between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andTenantIsNull() {
            addCriterion("Tenant is null");
            return (Criteria) this;
        }

        public Criteria andTenantIsNotNull() {
            addCriterion("Tenant is not null");
            return (Criteria) this;
        }

        public Criteria andTenantEqualTo(String value) {
            addCriterion("Tenant =", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotEqualTo(String value) {
            addCriterion("Tenant <>", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantGreaterThan(String value) {
            addCriterion("Tenant >", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantGreaterThanOrEqualTo(String value) {
            addCriterion("Tenant >=", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLessThan(String value) {
            addCriterion("Tenant <", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLessThanOrEqualTo(String value) {
            addCriterion("Tenant <=", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantLike(String value) {
            addCriterion("Tenant like", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotLike(String value) {
            addCriterion("Tenant not like", value, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantIn(List<String> values) {
            addCriterion("Tenant in", values, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotIn(List<String> values) {
            addCriterion("Tenant not in", values, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantBetween(String value1, String value2) {
            addCriterion("Tenant between", value1, value2, "tenant");
            return (Criteria) this;
        }

        public Criteria andTenantNotBetween(String value1, String value2) {
            addCriterion("Tenant not between", value1, value2, "tenant");
            return (Criteria) this;
        }

        public Criteria andRentalRateIsNull() {
            addCriterion("Rental_Rate is null");
            return (Criteria) this;
        }

        public Criteria andRentalRateIsNotNull() {
            addCriterion("Rental_Rate is not null");
            return (Criteria) this;
        }

        public Criteria andRentalRateEqualTo(BigDecimal value) {
            addCriterion("Rental_Rate =", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateNotEqualTo(BigDecimal value) {
            addCriterion("Rental_Rate <>", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateGreaterThan(BigDecimal value) {
            addCriterion("Rental_Rate >", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Rental_Rate >=", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateLessThan(BigDecimal value) {
            addCriterion("Rental_Rate <", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Rental_Rate <=", value, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateIn(List<BigDecimal> values) {
            addCriterion("Rental_Rate in", values, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateNotIn(List<BigDecimal> values) {
            addCriterion("Rental_Rate not in", values, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Rental_Rate between", value1, value2, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andRentalRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Rental_Rate not between", value1, value2, "rentalRate");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNull() {
            addCriterion("Total_amount is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNotNull() {
            addCriterion("Total_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountEqualTo(Integer value) {
            addCriterion("Total_amount =", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotEqualTo(Integer value) {
            addCriterion("Total_amount <>", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThan(Integer value) {
            addCriterion("Total_amount >", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Total_amount >=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThan(Integer value) {
            addCriterion("Total_amount <", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Total_amount <=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIn(List<Integer> values) {
            addCriterion("Total_amount in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotIn(List<Integer> values) {
            addCriterion("Total_amount not in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountBetween(Integer value1, Integer value2) {
            addCriterion("Total_amount between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Total_amount not between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIsNull() {
            addCriterion("\"Total_ area\" is null");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIsNotNull() {
            addCriterion("\"Total_ area\" is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAreaEqualTo(BigDecimal value) {
            addCriterion("\"Total_ area\" =", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotEqualTo(BigDecimal value) {
            addCriterion("\"Total_ area\" <>", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaGreaterThan(BigDecimal value) {
            addCriterion("\"Total_ area\" >", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("\"Total_ area\" >=", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLessThan(BigDecimal value) {
            addCriterion("\"Total_ area\" <", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("\"Total_ area\" <=", value, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaIn(List<BigDecimal> values) {
            addCriterion("\"Total_ area\" in", values, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotIn(List<BigDecimal> values) {
            addCriterion("\"Total_ area\" not in", values, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"Total_ area\" between", value1, value2, "totalArea");
            return (Criteria) this;
        }

        public Criteria andTotalAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("\"Total_ area\" not between", value1, value2, "totalArea");
            return (Criteria) this;
        }

        public Criteria andContractIsNull() {
            addCriterion("Contract is null");
            return (Criteria) this;
        }

        public Criteria andContractIsNotNull() {
            addCriterion("Contract is not null");
            return (Criteria) this;
        }

        public Criteria andContractEqualTo(String value) {
            addCriterion("Contract =", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotEqualTo(String value) {
            addCriterion("Contract <>", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractGreaterThan(String value) {
            addCriterion("Contract >", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractGreaterThanOrEqualTo(String value) {
            addCriterion("Contract >=", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLessThan(String value) {
            addCriterion("Contract <", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLessThanOrEqualTo(String value) {
            addCriterion("Contract <=", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLike(String value) {
            addCriterion("Contract like", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotLike(String value) {
            addCriterion("Contract not like", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractIn(List<String> values) {
            addCriterion("Contract in", values, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotIn(List<String> values) {
            addCriterion("Contract not in", values, "contract");
            return (Criteria) this;
        }

        public Criteria andContractBetween(String value1, String value2) {
            addCriterion("Contract between", value1, value2, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotBetween(String value1, String value2) {
            addCriterion("Contract not between", value1, value2, "contract");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("Start_Date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("Start_Date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("Start_Date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("Start_Date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("Start_Date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Start_Date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("Start_Date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("Start_Date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("Start_Date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("Start_Date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("Start_Date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("Start_Date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("End_Date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("End_Date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("End_Date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("End_Date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("End_Date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("End_Date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("End_Date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("End_Date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("End_Date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("End_Date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("End_Date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("End_Date not between", value1, value2, "endDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Items
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}