package com.generator.pojo;

public class RLmApplicationAttached {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.PK_Application_attachedID
     *
     * @mbggenerated
     */
    private String pkApplicationAttachedid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.FK_ ApplicationID
     *
     * @mbggenerated
     */
    private String fkApplicationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.FK_Attached_Type
     *
     * @mbggenerated
     */
    private String fkAttachedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.Attached_DocumentNo
     *
     * @mbggenerated
     */
    private String attachedDocumentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.FK_Application_ItemID
     *
     * @mbggenerated
     */
    private String fkApplicationItemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.FK_Application_Item _AssetID
     *
     * @mbggenerated
     */
    private String fkApplicationItemAssetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_attached.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.PK_Application_attachedID
     *
     * @return the value of R_LM_Application_attached.PK_Application_attachedID
     *
     * @mbggenerated
     */
    public String getPkApplicationAttachedid() {
        return pkApplicationAttachedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.PK_Application_attachedID
     *
     * @param pkApplicationAttachedid the value for R_LM_Application_attached.PK_Application_attachedID
     *
     * @mbggenerated
     */
    public void setPkApplicationAttachedid(String pkApplicationAttachedid) {
        this.pkApplicationAttachedid = pkApplicationAttachedid == null ? null : pkApplicationAttachedid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.FK_ ApplicationID
     *
     * @return the value of R_LM_Application_attached.FK_ ApplicationID
     *
     * @mbggenerated
     */
    public String getFkApplicationid() {
        return fkApplicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.FK_ ApplicationID
     *
     * @param fkApplicationid the value for R_LM_Application_attached.FK_ ApplicationID
     *
     * @mbggenerated
     */
    public void setFkApplicationid(String fkApplicationid) {
        this.fkApplicationid = fkApplicationid == null ? null : fkApplicationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.Name
     *
     * @return the value of R_LM_Application_attached.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.Name
     *
     * @param name the value for R_LM_Application_attached.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.FK_Attached_Type
     *
     * @return the value of R_LM_Application_attached.FK_Attached_Type
     *
     * @mbggenerated
     */
    public String getFkAttachedType() {
        return fkAttachedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.FK_Attached_Type
     *
     * @param fkAttachedType the value for R_LM_Application_attached.FK_Attached_Type
     *
     * @mbggenerated
     */
    public void setFkAttachedType(String fkAttachedType) {
        this.fkAttachedType = fkAttachedType == null ? null : fkAttachedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.Attached_DocumentNo
     *
     * @return the value of R_LM_Application_attached.Attached_DocumentNo
     *
     * @mbggenerated
     */
    public String getAttachedDocumentno() {
        return attachedDocumentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.Attached_DocumentNo
     *
     * @param attachedDocumentno the value for R_LM_Application_attached.Attached_DocumentNo
     *
     * @mbggenerated
     */
    public void setAttachedDocumentno(String attachedDocumentno) {
        this.attachedDocumentno = attachedDocumentno == null ? null : attachedDocumentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.FK_Application_ItemID
     *
     * @return the value of R_LM_Application_attached.FK_Application_ItemID
     *
     * @mbggenerated
     */
    public String getFkApplicationItemid() {
        return fkApplicationItemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.FK_Application_ItemID
     *
     * @param fkApplicationItemid the value for R_LM_Application_attached.FK_Application_ItemID
     *
     * @mbggenerated
     */
    public void setFkApplicationItemid(String fkApplicationItemid) {
        this.fkApplicationItemid = fkApplicationItemid == null ? null : fkApplicationItemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.FK_Application_Item _AssetID
     *
     * @return the value of R_LM_Application_attached.FK_Application_Item _AssetID
     *
     * @mbggenerated
     */
    public String getFkApplicationItemAssetid() {
        return fkApplicationItemAssetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.FK_Application_Item _AssetID
     *
     * @param fkApplicationItemAssetid the value for R_LM_Application_attached.FK_Application_Item _AssetID
     *
     * @mbggenerated
     */
    public void setFkApplicationItemAssetid(String fkApplicationItemAssetid) {
        this.fkApplicationItemAssetid = fkApplicationItemAssetid == null ? null : fkApplicationItemAssetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_attached.URL
     *
     * @return the value of R_LM_Application_attached.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_attached.URL
     *
     * @param url the value for R_LM_Application_attached.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}