package com.generator.pojo;

import java.util.ArrayList;
import java.util.List;

public class RLmApplicationAttachedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public RLmApplicationAttachedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkApplicationAttachedidIsNull() {
            addCriterion("PK_Application_attachedID is null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidIsNotNull() {
            addCriterion("PK_Application_attachedID is not null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidEqualTo(String value) {
            addCriterion("PK_Application_attachedID =", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidNotEqualTo(String value) {
            addCriterion("PK_Application_attachedID <>", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidGreaterThan(String value) {
            addCriterion("PK_Application_attachedID >", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidGreaterThanOrEqualTo(String value) {
            addCriterion("PK_Application_attachedID >=", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidLessThan(String value) {
            addCriterion("PK_Application_attachedID <", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidLessThanOrEqualTo(String value) {
            addCriterion("PK_Application_attachedID <=", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidLike(String value) {
            addCriterion("PK_Application_attachedID like", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidNotLike(String value) {
            addCriterion("PK_Application_attachedID not like", value, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidIn(List<String> values) {
            addCriterion("PK_Application_attachedID in", values, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidNotIn(List<String> values) {
            addCriterion("PK_Application_attachedID not in", values, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidBetween(String value1, String value2) {
            addCriterion("PK_Application_attachedID between", value1, value2, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationAttachedidNotBetween(String value1, String value2) {
            addCriterion("PK_Application_attachedID not between", value1, value2, "pkApplicationAttachedid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNull() {
            addCriterion("\"FK_ ApplicationID\" is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNotNull() {
            addCriterion("\"FK_ ApplicationID\" is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" =", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <>", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThan(String value) {
            addCriterion("\"FK_ ApplicationID\" >", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" >=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThan(String value) {
            addCriterion("\"FK_ ApplicationID\" <", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLike(String value) {
            addCriterion("\"FK_ ApplicationID\" like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotLike(String value) {
            addCriterion("\"FK_ ApplicationID\" not like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" not in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" not between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeIsNull() {
            addCriterion("FK_Attached_Type is null");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeIsNotNull() {
            addCriterion("FK_Attached_Type is not null");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeEqualTo(String value) {
            addCriterion("FK_Attached_Type =", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeNotEqualTo(String value) {
            addCriterion("FK_Attached_Type <>", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeGreaterThan(String value) {
            addCriterion("FK_Attached_Type >", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeGreaterThanOrEqualTo(String value) {
            addCriterion("FK_Attached_Type >=", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeLessThan(String value) {
            addCriterion("FK_Attached_Type <", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeLessThanOrEqualTo(String value) {
            addCriterion("FK_Attached_Type <=", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeLike(String value) {
            addCriterion("FK_Attached_Type like", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeNotLike(String value) {
            addCriterion("FK_Attached_Type not like", value, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeIn(List<String> values) {
            addCriterion("FK_Attached_Type in", values, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeNotIn(List<String> values) {
            addCriterion("FK_Attached_Type not in", values, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeBetween(String value1, String value2) {
            addCriterion("FK_Attached_Type between", value1, value2, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andFkAttachedTypeNotBetween(String value1, String value2) {
            addCriterion("FK_Attached_Type not between", value1, value2, "fkAttachedType");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoIsNull() {
            addCriterion("Attached_DocumentNo is null");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoIsNotNull() {
            addCriterion("Attached_DocumentNo is not null");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoEqualTo(String value) {
            addCriterion("Attached_DocumentNo =", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoNotEqualTo(String value) {
            addCriterion("Attached_DocumentNo <>", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoGreaterThan(String value) {
            addCriterion("Attached_DocumentNo >", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoGreaterThanOrEqualTo(String value) {
            addCriterion("Attached_DocumentNo >=", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoLessThan(String value) {
            addCriterion("Attached_DocumentNo <", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoLessThanOrEqualTo(String value) {
            addCriterion("Attached_DocumentNo <=", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoLike(String value) {
            addCriterion("Attached_DocumentNo like", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoNotLike(String value) {
            addCriterion("Attached_DocumentNo not like", value, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoIn(List<String> values) {
            addCriterion("Attached_DocumentNo in", values, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoNotIn(List<String> values) {
            addCriterion("Attached_DocumentNo not in", values, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoBetween(String value1, String value2) {
            addCriterion("Attached_DocumentNo between", value1, value2, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andAttachedDocumentnoNotBetween(String value1, String value2) {
            addCriterion("Attached_DocumentNo not between", value1, value2, "attachedDocumentno");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidIsNull() {
            addCriterion("FK_Application_ItemID is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidIsNotNull() {
            addCriterion("FK_Application_ItemID is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidEqualTo(String value) {
            addCriterion("FK_Application_ItemID =", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotEqualTo(String value) {
            addCriterion("FK_Application_ItemID <>", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidGreaterThan(String value) {
            addCriterion("FK_Application_ItemID >", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidGreaterThanOrEqualTo(String value) {
            addCriterion("FK_Application_ItemID >=", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidLessThan(String value) {
            addCriterion("FK_Application_ItemID <", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidLessThanOrEqualTo(String value) {
            addCriterion("FK_Application_ItemID <=", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidLike(String value) {
            addCriterion("FK_Application_ItemID like", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotLike(String value) {
            addCriterion("FK_Application_ItemID not like", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidIn(List<String> values) {
            addCriterion("FK_Application_ItemID in", values, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotIn(List<String> values) {
            addCriterion("FK_Application_ItemID not in", values, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidBetween(String value1, String value2) {
            addCriterion("FK_Application_ItemID between", value1, value2, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotBetween(String value1, String value2) {
            addCriterion("FK_Application_ItemID not between", value1, value2, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidIsNull() {
            addCriterion("\"FK_Application_Item _AssetID\" is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidIsNotNull() {
            addCriterion("\"FK_Application_Item _AssetID\" is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidEqualTo(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" =", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidNotEqualTo(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" <>", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidGreaterThan(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" >", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidGreaterThanOrEqualTo(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" >=", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidLessThan(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" <", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidLessThanOrEqualTo(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" <=", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidLike(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" like", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidNotLike(String value) {
            addCriterion("\"FK_Application_Item _AssetID\" not like", value, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidIn(List<String> values) {
            addCriterion("\"FK_Application_Item _AssetID\" in", values, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidNotIn(List<String> values) {
            addCriterion("\"FK_Application_Item _AssetID\" not in", values, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidBetween(String value1, String value2) {
            addCriterion("\"FK_Application_Item _AssetID\" between", value1, value2, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemAssetidNotBetween(String value1, String value2) {
            addCriterion("\"FK_Application_Item _AssetID\" not between", value1, value2, "fkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("URL is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("URL is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("URL =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("URL <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("URL >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("URL >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("URL <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("URL <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("URL like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("URL not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("URL in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("URL not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("URL between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("URL not between", value1, value2, "url");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_attached
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}