package com.generator.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RLmApplicationInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public RLmApplicationInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkApplicationidIsNull() {
            addCriterion("PK_ApplicationID is null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidIsNotNull() {
            addCriterion("PK_ApplicationID is not null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidEqualTo(String value) {
            addCriterion("PK_ApplicationID =", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidNotEqualTo(String value) {
            addCriterion("PK_ApplicationID <>", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidGreaterThan(String value) {
            addCriterion("PK_ApplicationID >", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidGreaterThanOrEqualTo(String value) {
            addCriterion("PK_ApplicationID >=", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidLessThan(String value) {
            addCriterion("PK_ApplicationID <", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidLessThanOrEqualTo(String value) {
            addCriterion("PK_ApplicationID <=", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidLike(String value) {
            addCriterion("PK_ApplicationID like", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidNotLike(String value) {
            addCriterion("PK_ApplicationID not like", value, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidIn(List<String> values) {
            addCriterion("PK_ApplicationID in", values, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidNotIn(List<String> values) {
            addCriterion("PK_ApplicationID not in", values, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidBetween(String value1, String value2) {
            addCriterion("PK_ApplicationID between", value1, value2, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationidNotBetween(String value1, String value2) {
            addCriterion("PK_ApplicationID not between", value1, value2, "pkApplicationid");
            return (Criteria) this;
        }

        public Criteria andDocumentNoIsNull() {
            addCriterion("Document_No is null");
            return (Criteria) this;
        }

        public Criteria andDocumentNoIsNotNull() {
            addCriterion("Document_No is not null");
            return (Criteria) this;
        }

        public Criteria andDocumentNoEqualTo(String value) {
            addCriterion("Document_No =", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoNotEqualTo(String value) {
            addCriterion("Document_No <>", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoGreaterThan(String value) {
            addCriterion("Document_No >", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoGreaterThanOrEqualTo(String value) {
            addCriterion("Document_No >=", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoLessThan(String value) {
            addCriterion("Document_No <", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoLessThanOrEqualTo(String value) {
            addCriterion("Document_No <=", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoLike(String value) {
            addCriterion("Document_No like", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoNotLike(String value) {
            addCriterion("Document_No not like", value, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoIn(List<String> values) {
            addCriterion("Document_No in", values, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoNotIn(List<String> values) {
            addCriterion("Document_No not in", values, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoBetween(String value1, String value2) {
            addCriterion("Document_No between", value1, value2, "documentNo");
            return (Criteria) this;
        }

        public Criteria andDocumentNoNotBetween(String value1, String value2) {
            addCriterion("Document_No not between", value1, value2, "documentNo");
            return (Criteria) this;
        }

        public Criteria andFkOrganidIsNull() {
            addCriterion("FK_OrganID is null");
            return (Criteria) this;
        }

        public Criteria andFkOrganidIsNotNull() {
            addCriterion("FK_OrganID is not null");
            return (Criteria) this;
        }

        public Criteria andFkOrganidEqualTo(Integer value) {
            addCriterion("FK_OrganID =", value, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidNotEqualTo(Integer value) {
            addCriterion("FK_OrganID <>", value, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidGreaterThan(Integer value) {
            addCriterion("FK_OrganID >", value, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidGreaterThanOrEqualTo(Integer value) {
            addCriterion("FK_OrganID >=", value, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidLessThan(Integer value) {
            addCriterion("FK_OrganID <", value, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidLessThanOrEqualTo(Integer value) {
            addCriterion("FK_OrganID <=", value, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidIn(List<Integer> values) {
            addCriterion("FK_OrganID in", values, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidNotIn(List<Integer> values) {
            addCriterion("FK_OrganID not in", values, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidBetween(Integer value1, Integer value2) {
            addCriterion("FK_OrganID between", value1, value2, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andFkOrganidNotBetween(Integer value1, Integer value2) {
            addCriterion("FK_OrganID not between", value1, value2, "fkOrganid");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueIsNull() {
            addCriterion("Total_Declared_Value is null");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueIsNotNull() {
            addCriterion("Total_Declared_Value is not null");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_Value =", value, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueNotEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_Value <>", value, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueGreaterThan(BigDecimal value) {
            addCriterion("Total_Declared_Value >", value, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_Value >=", value, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueLessThan(BigDecimal value) {
            addCriterion("Total_Declared_Value <", value, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_Value <=", value, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueIn(List<BigDecimal> values) {
            addCriterion("Total_Declared_Value in", values, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueNotIn(List<BigDecimal> values) {
            addCriterion("Total_Declared_Value not in", values, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Declared_Value between", value1, value2, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Declared_Value not between", value1, value2, "totalDeclaredValue");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountIsNull() {
            addCriterion("Total_Declared_amount is null");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountIsNotNull() {
            addCriterion("Total_Declared_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountEqualTo(Integer value) {
            addCriterion("Total_Declared_amount =", value, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountNotEqualTo(Integer value) {
            addCriterion("Total_Declared_amount <>", value, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountGreaterThan(Integer value) {
            addCriterion("Total_Declared_amount >", value, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("Total_Declared_amount >=", value, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountLessThan(Integer value) {
            addCriterion("Total_Declared_amount <", value, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountLessThanOrEqualTo(Integer value) {
            addCriterion("Total_Declared_amount <=", value, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountIn(List<Integer> values) {
            addCriterion("Total_Declared_amount in", values, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountNotIn(List<Integer> values) {
            addCriterion("Total_Declared_amount not in", values, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountBetween(Integer value1, Integer value2) {
            addCriterion("Total_Declared_amount between", value1, value2, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("Total_Declared_amount not between", value1, value2, "totalDeclaredAmount");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaIsNull() {
            addCriterion("Total_Declared_area is null");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaIsNotNull() {
            addCriterion("Total_Declared_area is not null");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_area =", value, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaNotEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_area <>", value, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaGreaterThan(BigDecimal value) {
            addCriterion("Total_Declared_area >", value, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_area >=", value, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaLessThan(BigDecimal value) {
            addCriterion("Total_Declared_area <", value, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Declared_area <=", value, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaIn(List<BigDecimal> values) {
            addCriterion("Total_Declared_area in", values, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaNotIn(List<BigDecimal> values) {
            addCriterion("Total_Declared_area not in", values, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Declared_area between", value1, value2, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andTotalDeclaredAreaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Declared_area not between", value1, value2, "totalDeclaredArea");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeIsNull() {
            addCriterion("Application_Type is null");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeIsNotNull() {
            addCriterion("Application_Type is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeEqualTo(String value) {
            addCriterion("Application_Type =", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotEqualTo(String value) {
            addCriterion("Application_Type <>", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeGreaterThan(String value) {
            addCriterion("Application_Type >", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Application_Type >=", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeLessThan(String value) {
            addCriterion("Application_Type <", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeLessThanOrEqualTo(String value) {
            addCriterion("Application_Type <=", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeLike(String value) {
            addCriterion("Application_Type like", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotLike(String value) {
            addCriterion("Application_Type not like", value, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeIn(List<String> values) {
            addCriterion("Application_Type in", values, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotIn(List<String> values) {
            addCriterion("Application_Type not in", values, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeBetween(String value1, String value2) {
            addCriterion("Application_Type between", value1, value2, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationTypeNotBetween(String value1, String value2) {
            addCriterion("Application_Type not between", value1, value2, "applicationType");
            return (Criteria) this;
        }

        public Criteria andApplicationDateIsNull() {
            addCriterion("Application_Date is null");
            return (Criteria) this;
        }

        public Criteria andApplicationDateIsNotNull() {
            addCriterion("Application_Date is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationDateEqualTo(Date value) {
            addCriterion("Application_Date =", value, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateNotEqualTo(Date value) {
            addCriterion("Application_Date <>", value, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateGreaterThan(Date value) {
            addCriterion("Application_Date >", value, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Application_Date >=", value, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateLessThan(Date value) {
            addCriterion("Application_Date <", value, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateLessThanOrEqualTo(Date value) {
            addCriterion("Application_Date <=", value, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateIn(List<Date> values) {
            addCriterion("Application_Date in", values, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateNotIn(List<Date> values) {
            addCriterion("Application_Date not in", values, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateBetween(Date value1, Date value2) {
            addCriterion("Application_Date between", value1, value2, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andApplicationDateNotBetween(Date value1, Date value2) {
            addCriterion("Application_Date not between", value1, value2, "applicationDate");
            return (Criteria) this;
        }

        public Criteria andHandlerIsNull() {
            addCriterion("Handler is null");
            return (Criteria) this;
        }

        public Criteria andHandlerIsNotNull() {
            addCriterion("Handler is not null");
            return (Criteria) this;
        }

        public Criteria andHandlerEqualTo(String value) {
            addCriterion("Handler =", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotEqualTo(String value) {
            addCriterion("Handler <>", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerGreaterThan(String value) {
            addCriterion("Handler >", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerGreaterThanOrEqualTo(String value) {
            addCriterion("Handler >=", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLessThan(String value) {
            addCriterion("Handler <", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLessThanOrEqualTo(String value) {
            addCriterion("Handler <=", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerLike(String value) {
            addCriterion("Handler like", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotLike(String value) {
            addCriterion("Handler not like", value, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerIn(List<String> values) {
            addCriterion("Handler in", values, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotIn(List<String> values) {
            addCriterion("Handler not in", values, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerBetween(String value1, String value2) {
            addCriterion("Handler between", value1, value2, "handler");
            return (Criteria) this;
        }

        public Criteria andHandlerNotBetween(String value1, String value2) {
            addCriterion("Handler not between", value1, value2, "handler");
            return (Criteria) this;
        }

        public Criteria andAuditorIsNull() {
            addCriterion("Auditor is null");
            return (Criteria) this;
        }

        public Criteria andAuditorIsNotNull() {
            addCriterion("Auditor is not null");
            return (Criteria) this;
        }

        public Criteria andAuditorEqualTo(String value) {
            addCriterion("Auditor =", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotEqualTo(String value) {
            addCriterion("Auditor <>", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorGreaterThan(String value) {
            addCriterion("Auditor >", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorGreaterThanOrEqualTo(String value) {
            addCriterion("Auditor >=", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorLessThan(String value) {
            addCriterion("Auditor <", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorLessThanOrEqualTo(String value) {
            addCriterion("Auditor <=", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorLike(String value) {
            addCriterion("Auditor like", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotLike(String value) {
            addCriterion("Auditor not like", value, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorIn(List<String> values) {
            addCriterion("Auditor in", values, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotIn(List<String> values) {
            addCriterion("Auditor not in", values, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorBetween(String value1, String value2) {
            addCriterion("Auditor between", value1, value2, "auditor");
            return (Criteria) this;
        }

        public Criteria andAuditorNotBetween(String value1, String value2) {
            addCriterion("Auditor not between", value1, value2, "auditor");
            return (Criteria) this;
        }

        public Criteria andSignerIsNull() {
            addCriterion("Signer is null");
            return (Criteria) this;
        }

        public Criteria andSignerIsNotNull() {
            addCriterion("Signer is not null");
            return (Criteria) this;
        }

        public Criteria andSignerEqualTo(String value) {
            addCriterion("Signer =", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerNotEqualTo(String value) {
            addCriterion("Signer <>", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerGreaterThan(String value) {
            addCriterion("Signer >", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerGreaterThanOrEqualTo(String value) {
            addCriterion("Signer >=", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerLessThan(String value) {
            addCriterion("Signer <", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerLessThanOrEqualTo(String value) {
            addCriterion("Signer <=", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerLike(String value) {
            addCriterion("Signer like", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerNotLike(String value) {
            addCriterion("Signer not like", value, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerIn(List<String> values) {
            addCriterion("Signer in", values, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerNotIn(List<String> values) {
            addCriterion("Signer not in", values, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerBetween(String value1, String value2) {
            addCriterion("Signer between", value1, value2, "signer");
            return (Criteria) this;
        }

        public Criteria andSignerNotBetween(String value1, String value2) {
            addCriterion("Signer not between", value1, value2, "signer");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("Phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("Phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("Phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("Phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("Phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("Phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("Phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("Phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("Phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("Phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("Phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("Phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("Phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("Phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewIsNull() {
            addCriterion("Is_Expert_Review is null");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewIsNotNull() {
            addCriterion("Is_Expert_Review is not null");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewEqualTo(Byte value) {
            addCriterion("Is_Expert_Review =", value, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewNotEqualTo(Byte value) {
            addCriterion("Is_Expert_Review <>", value, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewGreaterThan(Byte value) {
            addCriterion("Is_Expert_Review >", value, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewGreaterThanOrEqualTo(Byte value) {
            addCriterion("Is_Expert_Review >=", value, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewLessThan(Byte value) {
            addCriterion("Is_Expert_Review <", value, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewLessThanOrEqualTo(Byte value) {
            addCriterion("Is_Expert_Review <=", value, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewIn(List<Byte> values) {
            addCriterion("Is_Expert_Review in", values, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewNotIn(List<Byte> values) {
            addCriterion("Is_Expert_Review not in", values, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewBetween(Byte value1, Byte value2) {
            addCriterion("Is_Expert_Review between", value1, value2, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andIsExpertReviewNotBetween(Byte value1, Byte value2) {
            addCriterion("Is_Expert_Review not between", value1, value2, "isExpertReview");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("Status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("Status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("Is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("Is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Byte value) {
            addCriterion("Is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Byte value) {
            addCriterion("Is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Byte value) {
            addCriterion("Is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("Is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Byte value) {
            addCriterion("Is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("Is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Byte> values) {
            addCriterion("Is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Byte> values) {
            addCriterion("Is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
            addCriterion("Is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("Is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}