package com.generator.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class RLmApplicationItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.PK_Application_ItemID
     *
     * @mbggenerated
     */
    private String pkApplicationItemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.FK_ ApplicationID
     *
     * @mbggenerated
     */
    private String fkApplicationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Declared_Value
     *
     * @mbggenerated
     */
    private BigDecimal declaredValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Item_Type
     *
     * @mbggenerated
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Tenant
     *
     * @mbggenerated
     */
    private String tenant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Rental_Rate
     *
     * @mbggenerated
     */
    private BigDecimal rentalRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Total_amount
     *
     * @mbggenerated
     */
    private Integer totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Total_ area
     *
     * @mbggenerated
     */
    private BigDecimal totalArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Contract
     *
     * @mbggenerated
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.Start_Date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Items.End_Date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.PK_Application_ItemID
     *
     * @return the value of R_LM_Application_Items.PK_Application_ItemID
     *
     * @mbggenerated
     */
    public String getPkApplicationItemid() {
        return pkApplicationItemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.PK_Application_ItemID
     *
     * @param pkApplicationItemid the value for R_LM_Application_Items.PK_Application_ItemID
     *
     * @mbggenerated
     */
    public void setPkApplicationItemid(String pkApplicationItemid) {
        this.pkApplicationItemid = pkApplicationItemid == null ? null : pkApplicationItemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.FK_ ApplicationID
     *
     * @return the value of R_LM_Application_Items.FK_ ApplicationID
     *
     * @mbggenerated
     */
    public String getFkApplicationid() {
        return fkApplicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.FK_ ApplicationID
     *
     * @param fkApplicationid the value for R_LM_Application_Items.FK_ ApplicationID
     *
     * @mbggenerated
     */
    public void setFkApplicationid(String fkApplicationid) {
        this.fkApplicationid = fkApplicationid == null ? null : fkApplicationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Declared_Value
     *
     * @return the value of R_LM_Application_Items.Declared_Value
     *
     * @mbggenerated
     */
    public BigDecimal getDeclaredValue() {
        return declaredValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Declared_Value
     *
     * @param declaredValue the value for R_LM_Application_Items.Declared_Value
     *
     * @mbggenerated
     */
    public void setDeclaredValue(BigDecimal declaredValue) {
        this.declaredValue = declaredValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Item_Type
     *
     * @return the value of R_LM_Application_Items.Item_Type
     *
     * @mbggenerated
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Item_Type
     *
     * @param itemType the value for R_LM_Application_Items.Item_Type
     *
     * @mbggenerated
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Tenant
     *
     * @return the value of R_LM_Application_Items.Tenant
     *
     * @mbggenerated
     */
    public String getTenant() {
        return tenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Tenant
     *
     * @param tenant the value for R_LM_Application_Items.Tenant
     *
     * @mbggenerated
     */
    public void setTenant(String tenant) {
        this.tenant = tenant == null ? null : tenant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Rental_Rate
     *
     * @return the value of R_LM_Application_Items.Rental_Rate
     *
     * @mbggenerated
     */
    public BigDecimal getRentalRate() {
        return rentalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Rental_Rate
     *
     * @param rentalRate the value for R_LM_Application_Items.Rental_Rate
     *
     * @mbggenerated
     */
    public void setRentalRate(BigDecimal rentalRate) {
        this.rentalRate = rentalRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Total_amount
     *
     * @return the value of R_LM_Application_Items.Total_amount
     *
     * @mbggenerated
     */
    public Integer getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Total_amount
     *
     * @param totalAmount the value for R_LM_Application_Items.Total_amount
     *
     * @mbggenerated
     */
    public void setTotalAmount(Integer totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Total_ area
     *
     * @return the value of R_LM_Application_Items.Total_ area
     *
     * @mbggenerated
     */
    public BigDecimal getTotalArea() {
        return totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Total_ area
     *
     * @param totalArea the value for R_LM_Application_Items.Total_ area
     *
     * @mbggenerated
     */
    public void setTotalArea(BigDecimal totalArea) {
        this.totalArea = totalArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Contract
     *
     * @return the value of R_LM_Application_Items.Contract
     *
     * @mbggenerated
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Contract
     *
     * @param contract the value for R_LM_Application_Items.Contract
     *
     * @mbggenerated
     */
    public void setContract(String contract) {
        this.contract = contract == null ? null : contract.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.Start_Date
     *
     * @return the value of R_LM_Application_Items.Start_Date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.Start_Date
     *
     * @param startDate the value for R_LM_Application_Items.Start_Date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Items.End_Date
     *
     * @return the value of R_LM_Application_Items.End_Date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Items.End_Date
     *
     * @param endDate the value for R_LM_Application_Items.End_Date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}