package com.generator.pojo;

import java.math.BigDecimal;

public class RLmApplicationItemAssets {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.PK_Application_Item _AssetID
     *
     * @mbggenerated
     */
    private String pkApplicationItemAssetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.FK_ ApplicationID
     *
     * @mbggenerated
     */
    private String fkApplicationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.FK_Application_ItemID
     *
     * @mbggenerated
     */
    private String fkApplicationItemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.AssetID
     *
     * @mbggenerated
     */
    private String assetid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.Location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.Quantity_tobe_Leased
     *
     * @mbggenerated
     */
    private BigDecimal quantityTobeLeased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.Area_tobe_Leased
     *
     * @mbggenerated
     */
    private BigDecimal areaTobeLeased;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.Value
     *
     * @mbggenerated
     */
    private BigDecimal value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_LM_Application_Item_Assets.Remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.PK_Application_Item _AssetID
     *
     * @return the value of R_LM_Application_Item_Assets.PK_Application_Item _AssetID
     *
     * @mbggenerated
     */
    public String getPkApplicationItemAssetid() {
        return pkApplicationItemAssetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.PK_Application_Item _AssetID
     *
     * @param pkApplicationItemAssetid the value for R_LM_Application_Item_Assets.PK_Application_Item _AssetID
     *
     * @mbggenerated
     */
    public void setPkApplicationItemAssetid(String pkApplicationItemAssetid) {
        this.pkApplicationItemAssetid = pkApplicationItemAssetid == null ? null : pkApplicationItemAssetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.FK_ ApplicationID
     *
     * @return the value of R_LM_Application_Item_Assets.FK_ ApplicationID
     *
     * @mbggenerated
     */
    public String getFkApplicationid() {
        return fkApplicationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.FK_ ApplicationID
     *
     * @param fkApplicationid the value for R_LM_Application_Item_Assets.FK_ ApplicationID
     *
     * @mbggenerated
     */
    public void setFkApplicationid(String fkApplicationid) {
        this.fkApplicationid = fkApplicationid == null ? null : fkApplicationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.FK_Application_ItemID
     *
     * @return the value of R_LM_Application_Item_Assets.FK_Application_ItemID
     *
     * @mbggenerated
     */
    public String getFkApplicationItemid() {
        return fkApplicationItemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.FK_Application_ItemID
     *
     * @param fkApplicationItemid the value for R_LM_Application_Item_Assets.FK_Application_ItemID
     *
     * @mbggenerated
     */
    public void setFkApplicationItemid(String fkApplicationItemid) {
        this.fkApplicationItemid = fkApplicationItemid == null ? null : fkApplicationItemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.AssetID
     *
     * @return the value of R_LM_Application_Item_Assets.AssetID
     *
     * @mbggenerated
     */
    public String getAssetid() {
        return assetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.AssetID
     *
     * @param assetid the value for R_LM_Application_Item_Assets.AssetID
     *
     * @mbggenerated
     */
    public void setAssetid(String assetid) {
        this.assetid = assetid == null ? null : assetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.Location
     *
     * @return the value of R_LM_Application_Item_Assets.Location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.Location
     *
     * @param location the value for R_LM_Application_Item_Assets.Location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.Quantity_tobe_Leased
     *
     * @return the value of R_LM_Application_Item_Assets.Quantity_tobe_Leased
     *
     * @mbggenerated
     */
    public BigDecimal getQuantityTobeLeased() {
        return quantityTobeLeased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.Quantity_tobe_Leased
     *
     * @param quantityTobeLeased the value for R_LM_Application_Item_Assets.Quantity_tobe_Leased
     *
     * @mbggenerated
     */
    public void setQuantityTobeLeased(BigDecimal quantityTobeLeased) {
        this.quantityTobeLeased = quantityTobeLeased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.Area_tobe_Leased
     *
     * @return the value of R_LM_Application_Item_Assets.Area_tobe_Leased
     *
     * @mbggenerated
     */
    public BigDecimal getAreaTobeLeased() {
        return areaTobeLeased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.Area_tobe_Leased
     *
     * @param areaTobeLeased the value for R_LM_Application_Item_Assets.Area_tobe_Leased
     *
     * @mbggenerated
     */
    public void setAreaTobeLeased(BigDecimal areaTobeLeased) {
        this.areaTobeLeased = areaTobeLeased;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.Value
     *
     * @return the value of R_LM_Application_Item_Assets.Value
     *
     * @mbggenerated
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.Value
     *
     * @param value the value for R_LM_Application_Item_Assets.Value
     *
     * @mbggenerated
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_LM_Application_Item_Assets.Remarks
     *
     * @return the value of R_LM_Application_Item_Assets.Remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_LM_Application_Item_Assets.Remarks
     *
     * @param remarks the value for R_LM_Application_Item_Assets.Remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}