package com.generator.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RLmApplicationItemAssetsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public RLmApplicationItemAssetsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkApplicationItemAssetidIsNull() {
            addCriterion("\"PK_Application_Item _AssetID\" is null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidIsNotNull() {
            addCriterion("\"PK_Application_Item _AssetID\" is not null");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidEqualTo(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" =", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidNotEqualTo(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" <>", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidGreaterThan(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" >", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidGreaterThanOrEqualTo(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" >=", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidLessThan(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" <", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidLessThanOrEqualTo(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" <=", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidLike(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" like", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidNotLike(String value) {
            addCriterion("\"PK_Application_Item _AssetID\" not like", value, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidIn(List<String> values) {
            addCriterion("\"PK_Application_Item _AssetID\" in", values, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidNotIn(List<String> values) {
            addCriterion("\"PK_Application_Item _AssetID\" not in", values, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidBetween(String value1, String value2) {
            addCriterion("\"PK_Application_Item _AssetID\" between", value1, value2, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andPkApplicationItemAssetidNotBetween(String value1, String value2) {
            addCriterion("\"PK_Application_Item _AssetID\" not between", value1, value2, "pkApplicationItemAssetid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNull() {
            addCriterion("\"FK_ ApplicationID\" is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNotNull() {
            addCriterion("\"FK_ ApplicationID\" is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" =", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <>", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThan(String value) {
            addCriterion("\"FK_ ApplicationID\" >", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" >=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThan(String value) {
            addCriterion("\"FK_ ApplicationID\" <", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLike(String value) {
            addCriterion("\"FK_ ApplicationID\" like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotLike(String value) {
            addCriterion("\"FK_ ApplicationID\" not like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" not in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" not between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidIsNull() {
            addCriterion("FK_Application_ItemID is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidIsNotNull() {
            addCriterion("FK_Application_ItemID is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidEqualTo(String value) {
            addCriterion("FK_Application_ItemID =", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotEqualTo(String value) {
            addCriterion("FK_Application_ItemID <>", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidGreaterThan(String value) {
            addCriterion("FK_Application_ItemID >", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidGreaterThanOrEqualTo(String value) {
            addCriterion("FK_Application_ItemID >=", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidLessThan(String value) {
            addCriterion("FK_Application_ItemID <", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidLessThanOrEqualTo(String value) {
            addCriterion("FK_Application_ItemID <=", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidLike(String value) {
            addCriterion("FK_Application_ItemID like", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotLike(String value) {
            addCriterion("FK_Application_ItemID not like", value, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidIn(List<String> values) {
            addCriterion("FK_Application_ItemID in", values, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotIn(List<String> values) {
            addCriterion("FK_Application_ItemID not in", values, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidBetween(String value1, String value2) {
            addCriterion("FK_Application_ItemID between", value1, value2, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationItemidNotBetween(String value1, String value2) {
            addCriterion("FK_Application_ItemID not between", value1, value2, "fkApplicationItemid");
            return (Criteria) this;
        }

        public Criteria andAssetidIsNull() {
            addCriterion("AssetID is null");
            return (Criteria) this;
        }

        public Criteria andAssetidIsNotNull() {
            addCriterion("AssetID is not null");
            return (Criteria) this;
        }

        public Criteria andAssetidEqualTo(String value) {
            addCriterion("AssetID =", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidNotEqualTo(String value) {
            addCriterion("AssetID <>", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidGreaterThan(String value) {
            addCriterion("AssetID >", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidGreaterThanOrEqualTo(String value) {
            addCriterion("AssetID >=", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidLessThan(String value) {
            addCriterion("AssetID <", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidLessThanOrEqualTo(String value) {
            addCriterion("AssetID <=", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidLike(String value) {
            addCriterion("AssetID like", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidNotLike(String value) {
            addCriterion("AssetID not like", value, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidIn(List<String> values) {
            addCriterion("AssetID in", values, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidNotIn(List<String> values) {
            addCriterion("AssetID not in", values, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidBetween(String value1, String value2) {
            addCriterion("AssetID between", value1, value2, "assetid");
            return (Criteria) this;
        }

        public Criteria andAssetidNotBetween(String value1, String value2) {
            addCriterion("AssetID not between", value1, value2, "assetid");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("Location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("Location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("Location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("Location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("Location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("Location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("Location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("Location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("Location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("Location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("Location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("Location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("Location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("Location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedIsNull() {
            addCriterion("Quantity_tobe_Leased is null");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedIsNotNull() {
            addCriterion("Quantity_tobe_Leased is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedEqualTo(BigDecimal value) {
            addCriterion("Quantity_tobe_Leased =", value, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedNotEqualTo(BigDecimal value) {
            addCriterion("Quantity_tobe_Leased <>", value, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedGreaterThan(BigDecimal value) {
            addCriterion("Quantity_tobe_Leased >", value, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Quantity_tobe_Leased >=", value, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedLessThan(BigDecimal value) {
            addCriterion("Quantity_tobe_Leased <", value, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Quantity_tobe_Leased <=", value, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedIn(List<BigDecimal> values) {
            addCriterion("Quantity_tobe_Leased in", values, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedNotIn(List<BigDecimal> values) {
            addCriterion("Quantity_tobe_Leased not in", values, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Quantity_tobe_Leased between", value1, value2, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andQuantityTobeLeasedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Quantity_tobe_Leased not between", value1, value2, "quantityTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedIsNull() {
            addCriterion("Area_tobe_Leased is null");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedIsNotNull() {
            addCriterion("Area_tobe_Leased is not null");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedEqualTo(BigDecimal value) {
            addCriterion("Area_tobe_Leased =", value, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedNotEqualTo(BigDecimal value) {
            addCriterion("Area_tobe_Leased <>", value, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedGreaterThan(BigDecimal value) {
            addCriterion("Area_tobe_Leased >", value, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Area_tobe_Leased >=", value, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedLessThan(BigDecimal value) {
            addCriterion("Area_tobe_Leased <", value, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Area_tobe_Leased <=", value, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedIn(List<BigDecimal> values) {
            addCriterion("Area_tobe_Leased in", values, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedNotIn(List<BigDecimal> values) {
            addCriterion("Area_tobe_Leased not in", values, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Area_tobe_Leased between", value1, value2, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andAreaTobeLeasedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Area_tobe_Leased not between", value1, value2, "areaTobeLeased");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("Value is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("Value is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(BigDecimal value) {
            addCriterion("Value =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(BigDecimal value) {
            addCriterion("Value <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(BigDecimal value) {
            addCriterion("Value >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Value >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(BigDecimal value) {
            addCriterion("Value <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Value <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<BigDecimal> values) {
            addCriterion("Value in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<BigDecimal> values) {
            addCriterion("Value not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Value between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Value not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("Remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("Remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("Remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("Remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("Remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("Remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("Remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("Remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("Remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("Remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("Remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("Remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("Remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("Remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_Application_Item_Assets
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}