package com.generator.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RLmHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public RLmHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkLmHistoryidIsNull() {
            addCriterion("PK_LM_HistoryID is null");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidIsNotNull() {
            addCriterion("PK_LM_HistoryID is not null");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidEqualTo(String value) {
            addCriterion("PK_LM_HistoryID =", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidNotEqualTo(String value) {
            addCriterion("PK_LM_HistoryID <>", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidGreaterThan(String value) {
            addCriterion("PK_LM_HistoryID >", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidGreaterThanOrEqualTo(String value) {
            addCriterion("PK_LM_HistoryID >=", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidLessThan(String value) {
            addCriterion("PK_LM_HistoryID <", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidLessThanOrEqualTo(String value) {
            addCriterion("PK_LM_HistoryID <=", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidLike(String value) {
            addCriterion("PK_LM_HistoryID like", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidNotLike(String value) {
            addCriterion("PK_LM_HistoryID not like", value, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidIn(List<String> values) {
            addCriterion("PK_LM_HistoryID in", values, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidNotIn(List<String> values) {
            addCriterion("PK_LM_HistoryID not in", values, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidBetween(String value1, String value2) {
            addCriterion("PK_LM_HistoryID between", value1, value2, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andPkLmHistoryidNotBetween(String value1, String value2) {
            addCriterion("PK_LM_HistoryID not between", value1, value2, "pkLmHistoryid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNull() {
            addCriterion("\"FK_ ApplicationID\" is null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIsNotNull() {
            addCriterion("\"FK_ ApplicationID\" is not null");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" =", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <>", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThan(String value) {
            addCriterion("\"FK_ ApplicationID\" >", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidGreaterThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" >=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThan(String value) {
            addCriterion("\"FK_ ApplicationID\" <", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLessThanOrEqualTo(String value) {
            addCriterion("\"FK_ ApplicationID\" <=", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidLike(String value) {
            addCriterion("\"FK_ ApplicationID\" like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotLike(String value) {
            addCriterion("\"FK_ ApplicationID\" not like", value, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotIn(List<String> values) {
            addCriterion("\"FK_ ApplicationID\" not in", values, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andFkApplicationidNotBetween(String value1, String value2) {
            addCriterion("\"FK_ ApplicationID\" not between", value1, value2, "fkApplicationid");
            return (Criteria) this;
        }

        public Criteria andOperationIsNull() {
            addCriterion("Operation is null");
            return (Criteria) this;
        }

        public Criteria andOperationIsNotNull() {
            addCriterion("Operation is not null");
            return (Criteria) this;
        }

        public Criteria andOperationEqualTo(Byte value) {
            addCriterion("Operation =", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotEqualTo(Byte value) {
            addCriterion("Operation <>", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThan(Byte value) {
            addCriterion("Operation >", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThanOrEqualTo(Byte value) {
            addCriterion("Operation >=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThan(Byte value) {
            addCriterion("Operation <", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThanOrEqualTo(Byte value) {
            addCriterion("Operation <=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationIn(List<Byte> values) {
            addCriterion("Operation in", values, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotIn(List<Byte> values) {
            addCriterion("Operation not in", values, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationBetween(Byte value1, Byte value2) {
            addCriterion("Operation between", value1, value2, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotBetween(Byte value1, Byte value2) {
            addCriterion("Operation not between", value1, value2, "operation");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("Result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("Result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(Byte value) {
            addCriterion("Result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(Byte value) {
            addCriterion("Result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(Byte value) {
            addCriterion("Result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(Byte value) {
            addCriterion("Result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(Byte value) {
            addCriterion("Result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(Byte value) {
            addCriterion("Result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<Byte> values) {
            addCriterion("Result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<Byte> values) {
            addCriterion("Result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(Byte value1, Byte value2) {
            addCriterion("Result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(Byte value1, Byte value2) {
            addCriterion("Result not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("Remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("Remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("Remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("Remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("Remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("Remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("Remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("Remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("Remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("Remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("Remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("Remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("Remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("Remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIsNull() {
            addCriterion("Operation_Time is null");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIsNotNull() {
            addCriterion("Operation_Time is not null");
            return (Criteria) this;
        }

        public Criteria andOperationTimeEqualTo(Date value) {
            addCriterion("Operation_Time =", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotEqualTo(Date value) {
            addCriterion("Operation_Time <>", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeGreaterThan(Date value) {
            addCriterion("Operation_Time >", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Operation_Time >=", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeLessThan(Date value) {
            addCriterion("Operation_Time <", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeLessThanOrEqualTo(Date value) {
            addCriterion("Operation_Time <=", value, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeIn(List<Date> values) {
            addCriterion("Operation_Time in", values, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotIn(List<Date> values) {
            addCriterion("Operation_Time not in", values, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeBetween(Date value1, Date value2) {
            addCriterion("Operation_Time between", value1, value2, "operationTime");
            return (Criteria) this;
        }

        public Criteria andOperationTimeNotBetween(Date value1, Date value2) {
            addCriterion("Operation_Time not between", value1, value2, "operationTime");
            return (Criteria) this;
        }

        public Criteria andFkOperatorIsNull() {
            addCriterion("FK_Operator is null");
            return (Criteria) this;
        }

        public Criteria andFkOperatorIsNotNull() {
            addCriterion("FK_Operator is not null");
            return (Criteria) this;
        }

        public Criteria andFkOperatorEqualTo(Integer value) {
            addCriterion("FK_Operator =", value, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorNotEqualTo(Integer value) {
            addCriterion("FK_Operator <>", value, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorGreaterThan(Integer value) {
            addCriterion("FK_Operator >", value, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("FK_Operator >=", value, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorLessThan(Integer value) {
            addCriterion("FK_Operator <", value, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorLessThanOrEqualTo(Integer value) {
            addCriterion("FK_Operator <=", value, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorIn(List<Integer> values) {
            addCriterion("FK_Operator in", values, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorNotIn(List<Integer> values) {
            addCriterion("FK_Operator not in", values, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorBetween(Integer value1, Integer value2) {
            addCriterion("FK_Operator between", value1, value2, "fkOperator");
            return (Criteria) this;
        }

        public Criteria andFkOperatorNotBetween(Integer value1, Integer value2) {
            addCriterion("FK_Operator not between", value1, value2, "fkOperator");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_History
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table R_LM_History
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}