package com.generator.pojo;

public class ROmUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_OM_Users.PK_UserID
     *
     * @mbggenerated
     */
    private String pkUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_OM_Users.User_Name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_OM_Users.FK_OrganID
     *
     * @mbggenerated
     */
    private Integer fkOrganid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column R_OM_Users.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_OM_Users.PK_UserID
     *
     * @return the value of R_OM_Users.PK_UserID
     *
     * @mbggenerated
     */
    public String getPkUserid() {
        return pkUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_OM_Users.PK_UserID
     *
     * @param pkUserid the value for R_OM_Users.PK_UserID
     *
     * @mbggenerated
     */
    public void setPkUserid(String pkUserid) {
        this.pkUserid = pkUserid == null ? null : pkUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_OM_Users.User_Name
     *
     * @return the value of R_OM_Users.User_Name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_OM_Users.User_Name
     *
     * @param userName the value for R_OM_Users.User_Name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_OM_Users.FK_OrganID
     *
     * @return the value of R_OM_Users.FK_OrganID
     *
     * @mbggenerated
     */
    public Integer getFkOrganid() {
        return fkOrganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_OM_Users.FK_OrganID
     *
     * @param fkOrganid the value for R_OM_Users.FK_OrganID
     *
     * @mbggenerated
     */
    public void setFkOrganid(Integer fkOrganid) {
        this.fkOrganid = fkOrganid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column R_OM_Users.Password
     *
     * @return the value of R_OM_Users.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column R_OM_Users.Password
     *
     * @param password the value for R_OM_Users.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}